version: "3"

services:
    iris_prediction:
        build:
            context: prediction
            dockerfile: Dockerfile
        ports:
            - "82:81"   # host:container
        environment: 
            PORT: 81
        volumes:
            - ./prediction:/app
        restart: always
    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - "5001:5000"   
        environment: 
            PORT: 5000
        volumes:
            - ./frontend:/app
        restart: always
        depends_on:
            - iris_prediction
