version: "3"

services:
    iris_prediction:
        build:
            context: prediction
            dockerfile: Dockerfile.prediction_v3
        ports:
            - "80:5000"   
        environment: 
            PORT: 80 
        volumes:
            - ./prediction:/app
        restart: always
    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile.frontend
        ports:
            - "5000:5000"   
        environment: 
            PORT: 5000
        volumes:
            - ./frontend:/app
        restart: always
        depends_on:
            - iris_prediction
