version: "3"

services:
    iris_prediction:
        build:
            context: prediction
            dockerfile: Dockerfile
        ports:
            - "5000:5000"   
        environment: 
            PORT: 5000 
        volumes:
            - ./prediction:/app
        restart: always